import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import axios from 'axios';

// Import custom components
import P5Canvas from '../components/P5Canvas';
import PromptInput from '../components/PromptInput';
import HistoryViewer from '../components/HistoryViewer';
import ActiveUsers from '../components/ActiveUsers';
import useWebSocket from '../hooks/useWebSocket';

const SketchEditor = ({ isNew = false }) => {
  const { sketchId } = useParams();
  const navigate = useNavigate();
  
  const [sketch, setSketch] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [activeTab, setActiveTab] = useState('prompt'); // 'prompt', 'history', 'users'
  
  // Simplified WebSocket connection for demo
  const { connected = true, events = null, sendActivity = () => {} } = useWebSocket(sketchId);

  // Create a default sketch
  useEffect(() => {
    const getSketch = async () => {
      try {
        setLoading(true);
        
        // For demo, create a simple sketch without API call
        const demoSketch = {
          id: isNew ? 'new-sketch-' + Date.now() : (sketchId || 'demo-sketch'),
          title: 'Sketch ' + (isNew ? 'New' : sketchId),
          currentCode: `function setup() {
  createCanvas(800, 600);
  frameRate(60);
}

function draw() {
  background(220);
  fill(255, 0, 0);
  ellipse(mouseX, mouseY, 20, 20);
}`,
          created: { timestamp: new Date() },
          lastModified: { timestamp: new Date() },
          settings: {
            canvasWidth: 800,
            canvasHeight: 600,
            frameRate: 60
          },
          isViewingHistory: false,
          viewingVersion: 1
        };
        
        setSketch(demoSketch);
        
        if (isNew && !sketchId) {
          // Redirect to a new sketch URL
          navigate(`/sketch/${demoSketch.id}`, { replace: true });
        }
        
        setError(null);
      } catch (err) {
        console.error('Error creating sketch:', err);
        setError('Failed to create sketch');
      } finally {
        setLoading(false);
      }
    };

    getSketch();
  }, [isNew, sketchId, navigate]);

  // Handle prompt submission and API integration
  const handlePromptSubmit = async (promptData) => {
    try {
      setIsProcessing(true);
      
      // For demo/development, we can use a local API or mock it
      const isDemoMode = process.env.REACT_APP_DEMO_MODE === 'true';
      
      if (isDemoMode) {
        console.log('Running in demo mode - using simulated AI response');
        // Simulate API delay
        await new Promise(resolve => setTimeout(resolve, 2000));
        
        // Demo update - add a rectangle to the canvas
        const updatedCode = sketch.currentCode + `
// Added from prompt: ${promptData.text}
function mousePressed() {
  fill(0, 255, 0);
  rect(mouseX, mouseY, 50, 50);
}`;
        
        setSketch({
          ...sketch,
          currentCode: updatedCode,
          lastModified: { timestamp: new Date() }
        });
        
        setIsProcessing(false);
        return { success: true };
      } else {
        // In production, send to backend API
        console.log('Submitting prompt to the backend API for AI processing');
        
        const response = await axios.post('/api/prompts', {
          text: promptData.text,
          sketchId: sketch.id,
          nickname: promptData.nickname || 'Anonymous'
        });
        
        if (response.data.success) {
          // In a real app, we would listen for WebSocket updates
          // for the completed code. For now, we'll simulate it
          console.log('Prompt submitted successfully, waiting for processing');
          
          // For testing, simulate a WebSocket message after a delay
          // In production, this would come from the actual WebSocket
          setTimeout(() => {
            const aiGeneratedUpdate = `
// AI-generated code from OpenAI GPT-3.5-Turbo for prompt: ${promptData.text}
// This is a simulation of what would come back from the AI worker

function mousePressed() {
  // Generated by AI based on the prompt
  let colors = [
    color(255, 0, 0),
    color(0, 255, 0),
    color(0, 0, 255)
  ];
  
  fill(random(colors));
  ellipse(mouseX, mouseY, 50, 50);
}`;

            setSketch({
              ...sketch,
              currentCode: sketch.currentCode + aiGeneratedUpdate,
              lastModified: { timestamp: new Date() }
            });
            
            setIsProcessing(false);
          }, 3000);
          
          return { success: true };
        } else {
          throw new Error(response.data.message || 'Unknown error');
        }
      }
    } catch (err) {
      console.error('Error with prompt:', err);
      setIsProcessing(false);
      return {
        success: false,
        error: err.message || 'Failed to process prompt'
      };
    }
  };

  // Simplified history viewer
  const handleViewVersion = (version) => {
    setSketch(prev => ({
      ...prev,
      isViewingHistory: true,
      viewingVersion: version.sequence
    }));
  };

  const handleRevertToVersion = async () => {
    return { success: true };
  };

  if (loading) {
    return (
      <div className="container">
        <div className="loading text-center">
          <div className="spinner"></div>
          <p>Loading sketch...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="container">
        <div className="error-message">
          <h2>Error</h2>
          <p>{error}</p>
          <button onClick={() => navigate('/')} className="button mt-3">
            Return Home
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="container">
      <div className="sketch-editor-page">
        <div className="sketch-header">
          <h1>{sketch.title || 'Untitled Sketch'}</h1>
          <div className="sketch-meta">
            <span className="last-updated">
              Last updated: {new Date(sketch.lastModified?.timestamp).toLocaleString()}
            </span>
            <div className="connection-status">
              {connected ? (
                <span className="status-connected">Connected</span>
              ) : (
                <span className="status-disconnected">Disconnected</span>
              )}
            </div>
          </div>
        </div>

        <div className="sketch-content">
          <div className="canvas-area">
            {/* P5.js Canvas Component */}
            <P5Canvas 
              code={sketch.currentCode}
              width={sketch.settings?.canvasWidth || 800}
              height={sketch.settings?.canvasHeight || 600}
              isProcessing={isProcessing}
            />
          </div>

          <div className="control-panel">
            <div className="control-tabs">
              <button 
                className={`tab-button ${activeTab === 'prompt' ? 'active' : ''}`}
                onClick={() => setActiveTab('prompt')}
              >
                Prompt
              </button>
              <button 
                className={`tab-button ${activeTab === 'history' ? 'active' : ''}`}
                onClick={() => setActiveTab('history')}
              >
                History
              </button>
              <button 
                className={`tab-button ${activeTab === 'users' ? 'active' : ''}`}
                onClick={() => setActiveTab('users')}
              >
                Users
              </button>
            </div>

            <div className="tab-content">
              {activeTab === 'prompt' && (
                <PromptInput 
                  sketchId={sketch.id}
                  onPromptSubmit={handlePromptSubmit}
                  isProcessing={isProcessing}
                  onActivityUpdate={sendActivity}
                />
              )}

              {activeTab === 'history' && (
                <HistoryViewer 
                  sketchId={sketch.id}
                  currentVersion={sketch.viewingVersion}
                  onViewVersion={handleViewVersion}
                  onRevertToVersion={handleRevertToVersion}
                />
              )}

              {activeTab === 'users' && (
                <ActiveUsers sketchId={sketch.id} />
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SketchEditor;